//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMotivationITSupportHelpdesk_UNIT6_8_9_FINAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoMotivationITSupportHelpdeskDatabaseEntities : DbContext
    {
        public AutoMotivationITSupportHelpdeskDatabaseEntities()
            : base("name=AutoMotivationITSupportHelpdeskDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GeneralEmployeeAccount> GeneralEmployeeAccounts { get; set; }
        public virtual DbSet<ITSupportTechnicianAccount> ITSupportTechnicianAccounts { get; set; }
        public virtual DbSet<ITSupportTicket> ITSupportTickets { get; set; }
        public virtual DbSet<ManagerAccount> ManagerAccounts { get; set; }
    }
}
