//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMotivationITSupportHelpdesk_UNIT6_8_9_FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralEmployeeAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralEmployeeAccount()
        {
            this.ITSupportTickets = new HashSet<ITSupportTicket>();
        }
    
        public int GeneralEmployeeID { get; set; }
        public string GeneralEmployeeFirstName { get; set; }
        public string GeneralEmployeeLastName { get; set; }
        public string GeneralEmployeeUsername { get; set; }
        public string GeneralEmployeePassword { get; set; }
        public string GeneralEmployeeEmail { get; set; }
        public string GeneralEmployeePhoneNumber { get; set; }
        public System.DateTime AccountCreationTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITSupportTicket> ITSupportTickets { get; set; }
    }
}
