//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMotivationITSupportHelpdesk_UNIT6_8_9_FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITSupportTechnicianAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITSupportTechnicianAccount()
        {
            this.ITSupportTickets = new HashSet<ITSupportTicket>();
        }
    
        public int ITSupportTechnicianID { get; set; }
        public string ITSupportTechnicianFirstName { get; set; }
        public string ITSupportTechnicianLastName { get; set; }
        public string ITSupportTechnicianUsername { get; set; }
        public string ITSupportTechnicianPassword { get; set; }
        public string ITSupportTechnicianEmail { get; set; }
        public string ITSupportTechnicianPhoneNumber { get; set; }
        public string ITSupportTechnicianSpecialty { get; set; }
        public System.DateTime AccountCreationTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITSupportTicket> ITSupportTickets { get; set; }
    }
}
