//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMotivationITSupportHelpdesk_UNIT6_8_9_FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerAccount
    {
        public int ManagerID { get; set; }
        public string ManagerFirstName { get; set; }
        public string ManagerLastName { get; set; }
        public string ManagerUsername { get; set; }
        public string ManagerPassword { get; set; }
        public string ManagerEmail { get; set; }
        public string ManagerPhoneNumber { get; set; }
        public System.DateTime AccountCreationTime { get; set; }
    }
}
